//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.10 at 10:13:19 AM CEST 
//


package org.whipper.xml.suite;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.whipper.xml.suite package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.whipper.xml.suite
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link QuerySuite }
     * 
     */
    public QuerySuite createQuerySuite() {
        return new QuerySuite();
    }

    /**
     * Create an instance of {@link Queries }
     * 
     */
    public Queries createQueries() {
        return new Queries();
    }

    /**
     * Create an instance of {@link MetaQueries }
     * 
     */
    public MetaQueries createMetaQueries() {
        return new MetaQueries();
    }

    /**
     * Create an instance of {@link SimpleMetaQuery }
     * 
     */
    public SimpleMetaQuery createSimpleMetaQuery() {
        return new SimpleMetaQuery();
    }

    /**
     * Create an instance of {@link MultiQuery }
     * 
     */
    public MultiQuery createMultiQuery() {
        return new MultiQuery();
    }

    /**
     * Create an instance of {@link MultiMetaQuery }
     * 
     */
    public MultiMetaQuery createMultiMetaQuery() {
        return new MultiMetaQuery();
    }

    /**
     * Create an instance of {@link SimpleQuery }
     * 
     */
    public SimpleQuery createSimpleQuery() {
        return new SimpleQuery();
    }

    /**
     * Create an instance of {@link Sql }
     * 
     */
    public Sql createSql() {
        return new Sql();
    }

}
