//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.12 at 12:40:10 PM CEST 
//


package org.whipper.xml.suite;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for queries complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="queries">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element name="query" type="{}simpleQuery"/>
 *           &lt;element name="query-set" type="{}multiQuery"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="before-suite" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="after-suite" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="before-each" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="after-each" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "queries", propOrder = {
    "queryOrQuerySet"
})
public class Queries {

    @XmlElements({
        @XmlElement(name = "query", type = SimpleQuery.class),
        @XmlElement(name = "query-set", type = MultiQuery.class)
    })
    protected List<Object> queryOrQuerySet;
    @XmlAttribute(name = "before-suite")
    protected String beforeSuite;
    @XmlAttribute(name = "after-suite")
    protected String afterSuite;
    @XmlAttribute(name = "before-each")
    protected String beforeEach;
    @XmlAttribute(name = "after-each")
    protected String afterEach;

    /**
     * Gets the value of the queryOrQuerySet property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the queryOrQuerySet property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQueryOrQuerySet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SimpleQuery }
     * {@link MultiQuery }
     * 
     * 
     */
    public List<Object> getQueryOrQuerySet() {
        if (queryOrQuerySet == null) {
            queryOrQuerySet = new ArrayList<Object>();
        }
        return this.queryOrQuerySet;
    }

    /**
     * Gets the value of the beforeSuite property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBeforeSuite() {
        return beforeSuite;
    }

    /**
     * Sets the value of the beforeSuite property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBeforeSuite(String value) {
        this.beforeSuite = value;
    }

    /**
     * Gets the value of the afterSuite property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAfterSuite() {
        return afterSuite;
    }

    /**
     * Sets the value of the afterSuite property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAfterSuite(String value) {
        this.afterSuite = value;
    }

    /**
     * Gets the value of the beforeEach property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBeforeEach() {
        return beforeEach;
    }

    /**
     * Sets the value of the beforeEach property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBeforeEach(String value) {
        this.beforeEach = value;
    }

    /**
     * Gets the value of the afterEach property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAfterEach() {
        return afterEach;
    }

    /**
     * Sets the value of the afterEach property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAfterEach(String value) {
        this.afterEach = value;
    }

}
