//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.10 at 10:13:19 AM CEST 
//


package org.whipper.xml.suite;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="queries" type="{}queries"/>
 *         &lt;element name="meta-queries" type="{}metaQueries" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "queries",
    "metaQueries"
})
@XmlRootElement(name = "query-suite")
public class QuerySuite {

    @XmlElement(required = true)
    protected Queries queries;
    @XmlElement(name = "meta-queries")
    protected MetaQueries metaQueries;

    /**
     * Gets the value of the queries property.
     * 
     * @return
     *     possible object is
     *     {@link Queries }
     *     
     */
    public Queries getQueries() {
        return queries;
    }

    /**
     * Sets the value of the queries property.
     * 
     * @param value
     *     allowed object is
     *     {@link Queries }
     *     
     */
    public void setQueries(Queries value) {
        this.queries = value;
    }

    /**
     * Gets the value of the metaQueries property.
     * 
     * @return
     *     possible object is
     *     {@link MetaQueries }
     *     
     */
    public MetaQueries getMetaQueries() {
        return metaQueries;
    }

    /**
     * Sets the value of the metaQueries property.
     * 
     * @param value
     *     allowed object is
     *     {@link MetaQueries }
     *     
     */
    public void setMetaQueries(MetaQueries value) {
        this.metaQueries = value;
    }

}
